import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "../../context/Provider";
import NavbarComponent from "@/components/NavbarComponent";
import { Providers } from "./providers";
import FooterComponent from "@/components/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To-Do List APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <Providers>
            <div className="bg-orange-100 min-h-screen text-neutral-800">
              <NavbarComponent />
              {children}
              <FooterComponent/>
            </div>
          </Providers>
        </body>
      </Provider>
    </html>
  );
}
